- apt_key: keyserver=keyserver.ubuntu.com id="{{mongodb_apt_key_id}}"
  when: not mongodb_use_debian_package

- name: Install repo
  apt_repository: repo="{{mongodb_apt_repo}}" state=present
  when: not mongodb_use_debian_package

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Mongo from external MongoDB repository
  apt: pkg="mongodb-org={{mongodb_version}}" state=installed
  when: not mongodb_use_debian_package

- name: Install Mongo from default Debian repository
  apt: pkg="mongodb" state=installed
  when: mongodb_use_debian_package

- name: Ensure mongodb started and enabled
  service: name={{ 'mongodb' if mongodb_use_debian_package else 'mongod' }} state=started enabled=yes

- name: Configure mongodb
  template: src=mongod.conf.j2 dest=/etc/{{ 'mongodb' if mongodb_use_debian_package else 'mongod' }}.conf backup=yes owner=root group=root mode=0644
  notify: Restart mongodb

- name: Configure log rotation
  template: src=logrotate.conf.j2 dest=/etc/logrotate.d/{{ 'mongodb-server' if mongodb_use_debian_package else 'mongodb.conf' }}
  tags:
    - logrotate

## - name: Create the file to initialize the mongod replica set
##   template: src=repset_init.j2 dest=/tmp/repset_init.js
## 
## - name: Pause for a while
##   pause: seconds=20
## 
## - name: Initialize the replication set
##   shell: /usr/bin/mongo --port "{{ mongod_port }}" /tmp/repset_init.js
