---
# tasks file for ansible-mongodb

- include: install.yml
  tags: mongodb_install

##  Not working
## - include: replica.yml
##   tags: mongodb_replica

- include: replica2.yml
  tags: mongodb_replica
  when: is_master and mongodb_conf_replSet and mongodb_rs_initialize|bool
