- name: Check if repset_init has already be created
  stat: path=/tmp/repset_init.js
  register: repset_init

- name: Create the file to initialize the mongod replica set
  template: src=repset_init.j2 dest=/tmp/repset_init.js
  when: repset_init.stat.exists == False

- name: Restart mongodb to be sure is init repl state
  service: name={{ 'mongodb' if mongodb_use_debian_package else 'mongod' }} state=restarted
  when: repset_init.stat.exists == False

- name: Pause for a while
  pause: seconds=30
  when: repset_init.stat.exists == False

- name: Initialize the replication set
  shell: /usr/bin/mongo /tmp/repset_init.js
  when: repset_init.stat.exists == False
